services:
  # Backend (.NET API)
  - type: web
    name: controle-financeiro-api
    env: docker
    plan: free
    region: oregon
    buildCommand: docker build -t controle-financeiro-api .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DatabaseSettings__ConnectionString
        sync: false 

  # Frontend (Angular)
  - type: web
    name: controle-financeiro-web
    env: static
    plan: free
    rootDir: ControleFinanceiro-Web
    buildCommand: npm install && sed -i "s|API_URL_PLACEHOLDER|https://$API_URL|g" src/environments/environment.prod.ts && npm run build
    staticPublishPath: dist/controle-financeiro-web/browser
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /**
        destination: /index.html
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: controle-financeiro-api
          property: host
